/**
 * Every `defaultNow()` column is generated by MySQL, not by the app. The driver
 * writes and reads Dates as UTC, so if the server session keeps the host's CEST
 * clock those columns land two hours in the future — and any comparison against
 * a Date the app wrote (a 24h rate-limit window, "is the catalog newer than the
 * audit") silently uses the wrong instant.
 */
import { randomUUID } from 'node:crypto';
import { eq } from 'drizzle-orm';
import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { db } from '@/shared/db';
import { projects } from '@/shared/db/schema';
import { createUser, resetTables } from './helpers';

describe('MySQL server-generated timestamps', () => {
  beforeEach(resetTables);
  afterAll(async () => {
    await db.$client.end();
  });

  it('agree with the app clock, and with a Date the app wrote', async () => {
    const userId = await createUser();
    const id = randomUUID();
    const appWrote = new Date();
    await db.insert(projects).values({
      id,
      userId,
      name: 'tz',
      domain: 'tz.example.com',
      lastViewedAt: appWrote // app-supplied, for the cross-check below
    });

    const row = (await db.query.projects.findFirst({ where: eq(projects.id, id) }))!;
    const after = Date.now();

    // Seconds of slack: DATETIME truncates to the second, so two stamps taken
    // in the same millisecond can still land on adjacent seconds. The failure
    // this guards against is a whole time-zone offset — an hour or more.
    const SLACK_MS = 5000;
    expect(row.createdAt.getTime()).toBeGreaterThanOrEqual(appWrote.getTime() - SLACK_MS);
    expect(row.createdAt.getTime()).toBeLessThanOrEqual(after + SLACK_MS);
    // The pair that used to disagree: both sides must name the same instant.
    expect(Math.abs(row.createdAt.getTime() - row.lastViewedAt!.getTime())).toBeLessThan(SLACK_MS);
  });
});
