import { Card } from '@heroui/react';
import { ArrowRight, ExternalLink, Sparkles } from 'lucide-react';
import type { Metadata } from 'next';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { Link } from '@/i18n/navigation';
import { ProductImageGallery } from '@/components/product-image-gallery';
import { loadSharedAudit, type SharedProduct } from '@/lib/share/queries';

export const dynamic = 'force-dynamic';

interface PageProps {
  params: Promise<{ locale: string; token: string }>;
}

/**
 * Public, unauthenticated case-study page generated by an admin via
 * the dashboard's share-links card. Read-only — no actions, no nav
 * back into the merchant app.
 *
 * SEO: noindex/nofollow because each link is meant for one prospect;
 * having Google index them would expose customer-derived AI rewrites.
 */
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { token } = await params;
  const data = await loadSharedAudit(token);
  if (!data) return { title: 'Share link', robots: { index: false, follow: false } };
  return {
    title: `${data.domain} — case study`,
    robots: { index: false, follow: false },
    alternates: { canonical: undefined }
  };
}

export default async function SharePage({ params }: PageProps) {
  const { locale, token } = await params;
  setRequestLocale(locale);

  const data = await loadSharedAudit(token);
  if (!data) notFound();

  const t = await getTranslations('Share');

  return (
    <main className="flex-1 px-6 md:px-10 py-10 max-w-5xl w-full mx-auto flex flex-col gap-10">
      {/* Header ----------------------------------------------------- */}
      <header className="flex flex-col gap-3 text-center">
        <span className="eyebrow self-center">{t('publicEyebrow')}</span>
        {data.siteUrl ? (
          <a
            href={data.siteUrl}
            target="_blank"
            rel="noreferrer noopener"
            className="inline-flex items-center justify-center gap-2 self-center hover:text-[var(--accent)] transition-colors group"
          >
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight">
              {data.domain}
            </h1>
            <ExternalLink
              className="size-5 opacity-50 group-hover:opacity-100 transition-opacity shrink-0"
              aria-hidden
            />
          </a>
        ) : (
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight">
            {data.domain}
          </h1>
        )}
        <p className="text-sm text-[var(--muted)] max-w-2xl mx-auto leading-relaxed">
          {t('publicSubtitle', {
            platform: data.platform ?? 'your platform'
          })}
        </p>
      </header>

      {/* Audit summary ---------------------------------------------- */}
      {data.scores ? (
        <Card variant="secondary" className="p-6 flex flex-col gap-5">
          <div className="flex flex-col items-center gap-2">
            <span className="eyebrow">{t('overallScore')}</span>
            <span className="text-6xl font-bold tabular-nums">
              {data.scores.overall}
              <span className="text-2xl text-[var(--muted)] font-normal">/100</span>
            </span>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <ScoreBox label={t('axisCatalog')} value={data.scores.catalogCompleteness} />
            <ScoreBox label={t('axisCopy')} value={data.scores.copyQuality} />
            <ScoreBox label={t('axisVisual')} value={data.scores.visualQuality} />
            <ScoreBox label={t('axisTagging')} value={data.scores.taggingQuality} />
          </div>
        </Card>
      ) : null}

      {/* Products ---------------------------------------------------- */}
      <section className="flex flex-col gap-6">
        <h2 className="text-2xl font-bold tracking-tight text-center">
          {t('productsTitle')}
        </h2>
        <div className="flex flex-col gap-8">
          {data.products.map((p, idx) => (
            <ProductCaseStudy
              key={p.sourceId}
              index={idx + 1}
              product={p}
              labels={{
                source: t('sourceLabel'),
                ai: t('aiLabel'),
                title: t('fieldTitle'),
                description: t('fieldDescription'),
                tags: t('fieldTags'),
                images: t('fieldImages'),
                noTitle: t('noTitle'),
                noDescription: t('noDescription'),
                noTags: t('noTags'),
                noImages: t('noImages')
              }}
            />
          ))}
        </div>
      </section>

      {/* CTA --------------------------------------------------------- */}
      <Card variant="tertiary" className="p-6 flex flex-col items-center gap-3 text-center">
        <Sparkles className="size-6 text-[var(--accent)]" aria-hidden />
        <h2 className="text-xl font-bold tracking-tight">{t('ctaTitle')}</h2>
        <p className="text-sm text-[var(--muted)] max-w-xl leading-relaxed">
          {t('ctaSubtitle')}
        </p>
        <div className="flex items-center gap-3 mt-2">
          <Link
            href="/signup"
            className="px-4 py-2 rounded-md text-sm font-medium bg-[var(--accent)] text-[var(--accent-foreground)] hover:opacity-90 inline-flex items-center gap-1.5"
          >
            {t('ctaPrimary')}
            <ArrowRight className="size-3.5" />
          </Link>
          <Link
            href="/pricing"
            className="px-4 py-2 rounded-md text-sm font-medium border border-[var(--border)] hover:border-[var(--accent)]"
          >
            {t('ctaSecondary')}
          </Link>
        </div>
      </Card>

      <p className="text-xs text-[var(--muted)] text-center">
        {t('footerNote', { date: data.generatedAt.toLocaleDateString(locale) })}
      </p>
    </main>
  );
}

function ScoreBox({ label, value }: { label: string; value: number }) {
  const tone =
    value >= 75
      ? 'text-[var(--success)]'
      : value >= 50
        ? 'text-[var(--warning)]'
        : 'text-[var(--danger)]';
  return (
    <div className="flex flex-col items-center gap-1 p-3 rounded-md bg-[var(--background)] border border-[var(--border)]">
      <span className="text-xs text-[var(--muted)] uppercase tracking-wider font-mono">
        {label}
      </span>
      <span className={`text-2xl font-bold tabular-nums ${tone}`}>{value}</span>
    </div>
  );
}

/**
 * Per-product case study row. Layout:
 *
 *   - Header line: "#N — Product source title"
 *   - Title before/after: two columns (mobile-stacked) showing the
 *     pre-existing title vs the AI rewrite, side by side so the
 *     prospect can compare in one glance.
 *   - Body grid (3 columns on desktop, all stacked on mobile):
 *       - cols 1-2: Image gallery BEFORE + Image gallery AFTER, both
 *         rendered through <ProductImageGallery> for arrow-keys /
 *         chevrons / dot indicators (matches the carousel used on
 *         the per-product dashboard page).
 *       - col 3: Description (truncated, before then after) and Tags
 *         before/after, kept compact since this is a marketing page.
 *
 * Each section uses the full card width — on mobile, the columns
 * stack naturally and the images sit above the description.
 */
function ProductCaseStudy({
  index,
  product,
  labels
}: {
  index: number;
  product: SharedProduct;
  labels: {
    source: string;
    ai: string;
    title: string;
    description: string;
    tags: string;
    images: string;
    noTitle: string;
    noDescription: string;
    noTags: string;
    noImages: string;
  };
}) {
  const sourceDescriptionPlain = product.source.descriptionHtml
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const aiDescriptionPlain = (product.ai.descriptionHtml ?? '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  const sourceImages = product.source.images;
  const aiImages = product.ai.imageUrls.map((url, i) => ({
    src: url,
    alt: `AI image ${i + 1}`
  }));

  return (
    <Card variant="secondary" className="p-6 flex flex-col gap-6 w-full">
      {/* Header ----------------------------------------------------- */}
      <h3 className="text-xl md:text-2xl font-bold tracking-tight">
        <span className="text-[var(--muted)] mr-2">#{index}</span>
        {product.title}
      </h3>

      {/* Title before / after -------------------------------------- */}
      <div className="grid md:grid-cols-2 gap-3 p-4 rounded-md bg-[var(--default)]/40 border border-[var(--border)]">
        <TitleColumn
          label={labels.source}
          title={product.title}
          tone="muted"
        />
        <TitleColumn
          label={labels.ai}
          title={product.ai.title}
          fallback={labels.noTitle}
          tone="accent"
        />
      </div>

      {/* Body grid: images (2 cols) + sidebar text (1 col) ---------- */}
      <div className="grid md:grid-cols-3 gap-5">
        {/* Image carousels ----------------------------------------- */}
        <div className="md:col-span-2 grid sm:grid-cols-2 gap-4">
          <GalleryColumn
            label={labels.source}
            ariaLabel={labels.images}
            images={sourceImages}
            emptyLabel={labels.noImages}
            tone="muted"
          />
          <GalleryColumn
            label={labels.ai}
            ariaLabel={labels.images}
            images={aiImages}
            emptyLabel={labels.noImages}
            tone="accent"
          />
        </div>

        {/* Sidebar — descriptions + tags --------------------------- */}
        <aside className="flex flex-col gap-4">
          <DescriptionPair
            heading={labels.description}
            sourceLabel={labels.source}
            aiLabel={labels.ai}
            sourceText={sourceDescriptionPlain}
            aiText={aiDescriptionPlain}
            empty={labels.noDescription}
          />
          <TagsPair
            heading={labels.tags}
            sourceLabel={labels.source}
            aiLabel={labels.ai}
            sourceTags={product.source.tags}
            aiTags={product.ai.tags}
            empty={labels.noTags}
          />
        </aside>
      </div>
    </Card>
  );
}

function TitleColumn({
  label,
  title,
  fallback,
  tone
}: {
  label: string;
  title: string | null;
  fallback?: string;
  tone: 'muted' | 'accent';
}) {
  const showsFallback = !title || !title.trim();
  return (
    <div className="flex flex-col gap-1.5">
      <span
        className={`text-[10px] uppercase tracking-wider font-mono inline-flex items-center gap-1.5 ${
          tone === 'accent' ? 'text-[var(--accent)]' : 'text-[var(--muted)]'
        }`}
      >
        {label}
        {tone === 'accent' ? (
          <Sparkles className="size-3" aria-hidden />
        ) : null}
      </span>
      <p
        className={`text-sm md:text-base font-medium leading-relaxed ${
          showsFallback ? 'text-[var(--muted)] italic' : ''
        }`}
      >
        {title?.trim() ? title : fallback ?? ''}
      </p>
    </div>
  );
}

function GalleryColumn({
  label,
  ariaLabel,
  images,
  emptyLabel,
  tone
}: {
  label: string;
  ariaLabel: string;
  images: Array<{ src: string; alt: string | null }>;
  emptyLabel: string;
  tone: 'muted' | 'accent';
}) {
  return (
    <div className="flex flex-col gap-2">
      <span
        className={`text-[10px] uppercase tracking-wider font-mono inline-flex items-center gap-1.5 ${
          tone === 'accent' ? 'text-[var(--accent)]' : 'text-[var(--muted)]'
        }`}
      >
        {label}
        {tone === 'accent' ? (
          <Sparkles className="size-3" aria-hidden />
        ) : null}
      </span>
      <div
        role="region"
        aria-label={`${label} — ${ariaLabel}`}
        className="rounded-md overflow-hidden border border-[var(--border)]"
      >
        <ProductImageGallery
          images={images}
          aspect="aspect-square"
          emptyLabel={emptyLabel}
        />
      </div>
    </div>
  );
}

function DescriptionPair({
  heading,
  sourceLabel,
  aiLabel,
  sourceText,
  aiText,
  empty
}: {
  heading: string;
  sourceLabel: string;
  aiLabel: string;
  sourceText: string;
  aiText: string;
  empty: string;
}) {
  return (
    <div className="flex flex-col gap-2.5">
      <span className="text-xs font-mono uppercase tracking-wider text-[var(--muted)]">
        {heading}
      </span>
      <DescriptionBlock label={sourceLabel} text={sourceText} empty={empty} tone="muted" />
      <DescriptionBlock label={aiLabel} text={aiText} empty={empty} tone="accent" />
    </div>
  );
}

function DescriptionBlock({
  label,
  text,
  empty,
  tone
}: {
  label: string;
  text: string;
  empty: string;
  tone: 'muted' | 'accent';
}) {
  const isEmpty = !text;
  return (
    <div
      className={`flex flex-col gap-1 p-2.5 rounded-md border ${
        tone === 'accent'
          ? 'border-[var(--accent)]/30 bg-[var(--accent)]/5'
          : 'border-[var(--border)] bg-[var(--default)]/40'
      }`}
    >
      <span
        className={`text-[10px] uppercase tracking-wider font-mono inline-flex items-center gap-1 ${
          tone === 'accent' ? 'text-[var(--accent)]' : 'text-[var(--muted)]'
        }`}
      >
        {label}
        {tone === 'accent' ? <Sparkles className="size-3" aria-hidden /> : null}
      </span>
      <p
        className={`text-xs leading-relaxed line-clamp-4 ${
          isEmpty ? 'text-[var(--muted)] italic' : ''
        }`}
      >
        {isEmpty ? empty : text}
      </p>
    </div>
  );
}

function TagsPair({
  heading,
  sourceLabel,
  aiLabel,
  sourceTags,
  aiTags,
  empty
}: {
  heading: string;
  sourceLabel: string;
  aiLabel: string;
  sourceTags: string[];
  aiTags: string[];
  empty: string;
}) {
  return (
    <div className="flex flex-col gap-2.5">
      <span className="text-xs font-mono uppercase tracking-wider text-[var(--muted)]">
        {heading}
      </span>
      <TagsBlock label={sourceLabel} tags={sourceTags} empty={empty} tone="muted" />
      <TagsBlock label={aiLabel} tags={aiTags} empty={empty} tone="accent" />
    </div>
  );
}

function TagsBlock({
  label,
  tags,
  empty,
  tone
}: {
  label: string;
  tags: string[];
  empty: string;
  tone: 'muted' | 'accent';
}) {
  return (
    <div
      className={`flex flex-col gap-1.5 p-2.5 rounded-md border ${
        tone === 'accent'
          ? 'border-[var(--accent)]/30 bg-[var(--accent)]/5'
          : 'border-[var(--border)] bg-[var(--default)]/40'
      }`}
    >
      <span
        className={`text-[10px] uppercase tracking-wider font-mono inline-flex items-center gap-1 ${
          tone === 'accent' ? 'text-[var(--accent)]' : 'text-[var(--muted)]'
        }`}
      >
        {label}
        {tone === 'accent' ? <Sparkles className="size-3" aria-hidden /> : null}
      </span>
      {tags.length === 0 ? (
        <span className="text-xs text-[var(--muted)] italic">{empty}</span>
      ) : (
        <div className="flex flex-wrap gap-1">
          {tags.map((tag, i) => (
            <span
              key={`${tag}-${i}`}
              className={`text-[10px] px-1.5 py-0.5 rounded font-mono ${
                tone === 'accent'
                  ? 'bg-[var(--accent)]/15 text-[var(--accent)]'
                  : 'bg-[var(--default)] text-[var(--muted)]'
              }`}
            >
              {tag}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}
