import { Card } from '@heroui/react';
import { ArrowRight, ChevronDown, ExternalLink, ImageIcon, Sparkles } from 'lucide-react';
import type { Metadata } from 'next';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { Link } from '@/i18n/navigation';
import { ImageZoom } from '@/shared/ui';
import { decodeHtmlEntities } from '@/entities/store-adapter';
import {
  loadSharedAudit,
  type SharedAuditSnapshot,
  type SharedProduct
} from '@/entities/share-link';
import { translateIssueText } from '@/entities/share-link';
import { formatDate } from '@/shared/lib';

export const dynamic = 'force-dynamic';

interface PageProps {
  params: Promise<{ locale: string; token: string }>;
}

/**
 * Public, unauthenticated case-study page generated by an admin via
 * the dashboard's share-links card. Read-only — no actions, no nav
 * back into the merchant app.
 *
 * SEO: noindex/nofollow because each link is meant for one prospect;
 * having Google index them would expose customer-derived AI rewrites.
 */
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { token } = await params;
  const data = await loadSharedAudit(token);
  if (!data) return { title: 'Share link', robots: { index: false, follow: false } };
  return {
    title: `${data.domain} — case study`,
    robots: { index: false, follow: false },
    alternates: { canonical: undefined }
  };
}

export default async function SharePage({ params }: PageProps) {
  const { locale, token } = await params;
  setRequestLocale(locale);

  const data = await loadSharedAudit(token);
  if (!data) notFound();

  const t = await getTranslations('Share');
  const tIssues = await getTranslations('Issues');
  const tReport = await getTranslations('Report');

  return (
    <main className="flex-1 px-4 md:px-10 py-6 md:py-10 max-w-5xl w-full mx-auto flex flex-col gap-8 md:gap-10">
      {/* Header ----------------------------------------------------- */}
      <header className="flex flex-col gap-3 text-center">
        <span className="eyebrow self-center">{t('publicEyebrow')}</span>
        {data.siteUrl ? (
          // `min-w-0 max-w-full` on the link + `[overflow-wrap:anywhere]`
          // on the heading lets a really long domain wrap onto two
          // lines at any character (hostnames are typically one
          // "word", so break-words alone wouldn't help). Prevents
          // the heading from forcing horizontal scroll on narrow
          // viewports.
          <a
            href={data.siteUrl}
            target="_blank"
            rel="noreferrer noopener"
            className="inline-flex items-center justify-center gap-2 self-center min-w-0 max-w-full hover:text-[var(--accent)] transition-colors group"
          >
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight [overflow-wrap:anywhere] min-w-0">
              {data.domain}
            </h1>
            <ExternalLink
              className="size-5 opacity-50 group-hover:opacity-100 transition-opacity shrink-0"
              aria-hidden
            />
          </a>
        ) : (
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight [overflow-wrap:anywhere] self-center max-w-full">
            {data.domain}
          </h1>
        )}
        <p className="text-sm text-[var(--muted)] max-w-2xl mx-auto leading-relaxed">
          {t('publicSubtitle', {
            platform: data.platform ?? 'your platform'
          })}
        </p>
      </header>

      {/* Audit summary ---------------------------------------------- */}
      {data.scores ? (
        <Card variant="secondary" className="p-6 flex flex-col gap-5">
          <div className="flex flex-col items-center gap-2">
            <span className="eyebrow">{t('overallScore')}</span>
            <span className="text-6xl font-bold tabular-nums">
              {data.scores.overall}
              <span className="text-2xl text-[var(--muted)] font-normal">/100</span>
            </span>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <ScoreBox label={t('axisCatalog')} value={data.scores.catalogCompleteness} />
            <ScoreBox label={t('axisCopy')} value={data.scores.copyQuality} />
            <ScoreBox label={t('axisVisual')} value={data.scores.visualQuality} />
            <ScoreBox label={t('axisTagging')} value={data.scores.taggingQuality} />
          </div>

          {/* Collapsible "audit detail" — kept inside the scores card so
              the layout reads as one block. Closed by default so the
              before/after products below stay visible without
              scrolling past a wall of stats. */}
          {data.details ? (
            <AuditDetailDisclosure
              details={data.details}
              labels={{
                toggle: t('detailToggle'),
                toggleHide: t('detailToggleHide'),
                statsTitle: tReport('quickStats'),
                avgScore: tReport('avgScore'),
                avgImages: tReport('avgImages'),
                avgDescLength: tReport('avgDescLength'),
                avgTags: tReport('avgTags'),
                productsNoImage: tReport('productsNoImage'),
                productsNoDesc: tReport('productsNoDesc'),
                productsNoTags: t('detailProductsNoTags'),
                productsNoAlt: t('detailProductsNoAlt'),
                worstTitle: t('detailWorstTitle'),
                worstHint: t('detailWorstHint'),
                sampledLabel: t.raw('detailSampledLabel'),
                charsSuffix: t('detailCharsSuffix'),
                issuesLabel: t('detailIssuesLabel')
              }}
              translateIssue={(issue) => translateIssueText(tIssues, issue)}
            />
          ) : null}
        </Card>
      ) : null}

      {/* Products ---------------------------------------------------- */}
      <section className="flex flex-col gap-6">
        <h2 className="text-2xl font-bold tracking-tight text-center">{t('productsTitle')}</h2>
        <div className="flex flex-col gap-8">
          {data.products.map((p, idx) => (
            <ProductCaseStudy
              key={p.sourceId}
              index={idx + 1}
              product={p}
              labels={{
                source: t('sourceLabel'),
                ai: t('aiLabel'),
                title: t('fieldTitle'),
                description: t('fieldDescription'),
                tags: t('fieldTags'),
                images: t('fieldImages'),
                noTitle: t('noTitle'),
                noDescription: t('noDescription'),
                noTags: t('noTags'),
                noImages: t('noImages')
              }}
            />
          ))}
        </div>
      </section>

      {/* CTA --------------------------------------------------------- */}
      <Card variant="tertiary" className="p-6 flex flex-col items-center gap-3 text-center">
        <Sparkles className="size-6 text-[var(--accent)]" aria-hidden />
        <h2 className="text-xl font-bold tracking-tight">{t('ctaTitle')}</h2>
        <p className="text-sm text-[var(--muted)] max-w-xl leading-relaxed">{t('ctaSubtitle')}</p>
        <div className="flex items-center gap-3 mt-2">
          <Link
            href="/signup"
            className="px-4 py-2 rounded-md text-sm font-medium bg-[var(--accent)] text-[var(--accent-foreground)] hover:opacity-90 inline-flex items-center gap-1.5"
          >
            {t('ctaPrimary')}
            <ArrowRight className="size-3.5" />
          </Link>
          <Link
            href="/pricing"
            className="px-4 py-2 rounded-md text-sm font-medium border border-[var(--border)] hover:border-[var(--accent)]"
          >
            {t('ctaSecondary')}
          </Link>
        </div>
      </Card>

      <p className="text-xs text-[var(--muted)] text-center">
        {t('footerNote', { date: formatDate(data.generatedAt) })}
      </p>
    </main>
  );
}

interface AuditDetailLabels {
  toggle: string;
  toggleHide: string;
  statsTitle: string;
  avgScore: string;
  avgImages: string;
  avgDescLength: string;
  avgTags: string;
  productsNoImage: string;
  productsNoDesc: string;
  productsNoTags: string;
  productsNoAlt: string;
  worstTitle: string;
  worstHint: string;
  sampledLabel: string;
  charsSuffix: string;
  issuesLabel: string;
}

function AuditDetailDisclosure({
  details,
  labels,
  translateIssue
}: {
  details: NonNullable<SharedAuditSnapshot['details']>;
  labels: AuditDetailLabels;
  translateIssue: (issue: { code: string; data?: Record<string, string | number> }) => string;
}) {
  // Render statistic tiles only when the backing field is present so
  // legacy audits don't show "—" everywhere.
  const stats: Array<{ label: string; value: string }> = [];
  if (details.avgProductScore != null) {
    stats.push({
      label: labels.avgScore,
      value: `${Math.round(details.avgProductScore)} / 100`
    });
  }
  if (details.averages.imageCount != null) {
    stats.push({
      label: labels.avgImages,
      value: details.averages.imageCount.toFixed(1)
    });
  }
  if (details.averages.descriptionLength != null) {
    stats.push({
      label: labels.avgDescLength,
      value: `${Math.round(details.averages.descriptionLength)} ${labels.charsSuffix}`
    });
  }
  if (details.averages.tagCount != null) {
    stats.push({
      label: labels.avgTags,
      value: details.averages.tagCount.toFixed(1)
    });
  }
  if (details.distribution.imagesZero != null) {
    stats.push({
      label: labels.productsNoImage,
      value: String(details.distribution.imagesZero)
    });
  }
  if (details.distribution.descEmpty != null) {
    stats.push({
      label: labels.productsNoDesc,
      value: String(details.distribution.descEmpty)
    });
  }
  if (details.distribution.tagsZero != null) {
    stats.push({
      label: labels.productsNoTags,
      value: String(details.distribution.tagsZero)
    });
  }
  if (details.distribution.altNone != null) {
    stats.push({
      label: labels.productsNoAlt,
      value: String(details.distribution.altNone)
    });
  }

  const hasContent = stats.length > 0 || details.worstProducts.length > 0;
  if (!hasContent) return null;

  return (
    <details className="group rounded-md border border-[var(--border)] bg-[var(--background)]/40 mt-1">
      <summary className="flex items-center justify-between gap-2 cursor-pointer list-none px-4 py-3 text-sm font-medium hover:text-[var(--accent)] transition-colors [&::-webkit-details-marker]:hidden">
        <span className="inline-flex items-center gap-2">
          {labels.toggle}
          {details.sampled != null ? (
            <span className="text-xs text-[var(--muted)] font-normal">
              · {labels.sampledLabel.replace('{count}', String(details.sampled))}
            </span>
          ) : null}
        </span>
        <ChevronDown
          className="size-4 shrink-0 text-[var(--muted)] transition-transform duration-200 group-open:rotate-180"
          aria-hidden
        />
      </summary>
      <div className="px-4 pb-4 flex flex-col gap-5 text-sm">
        {stats.length > 0 ? (
          <div className="flex flex-col gap-2">
            <span className="text-xs uppercase tracking-wider text-[var(--muted)] font-medium">
              {labels.statsTitle}
            </span>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
              {stats.map((s) => (
                <div
                  key={s.label}
                  className="px-3 py-2 rounded-md bg-[var(--default)]/40 border border-[var(--border)]"
                >
                  <div className="text-[10px] uppercase tracking-wider text-[var(--muted)] font-mono">
                    {s.label}
                  </div>
                  <div className="text-base font-semibold mt-0.5 tabular-nums">{s.value}</div>
                </div>
              ))}
            </div>
          </div>
        ) : null}

        {details.worstProducts.length > 0 ? (
          <div className="flex flex-col gap-2">
            <span className="text-xs uppercase tracking-wider text-[var(--muted)] font-medium">
              {labels.worstTitle}
            </span>
            <p className="text-xs text-[var(--muted)] leading-relaxed">{labels.worstHint}</p>
            <ul className="flex flex-col gap-2">
              {details.worstProducts.map((p, idx) => {
                const title = decodeHtmlEntities(p.title ?? '');
                return (
                  <li
                    key={`${idx}-${title}`}
                    className="px-3 py-2 rounded-md bg-[var(--default)]/40 border border-[var(--border)] flex flex-col gap-1"
                  >
                    <div className="flex items-baseline justify-between gap-3">
                      <span className="font-medium text-sm truncate">{title}</span>
                      <span className="text-xs font-mono tabular-nums text-[var(--muted)] shrink-0">
                        {p.score}/100
                      </span>
                    </div>
                    {p.issues.length > 0 ? (
                      <p className="text-xs text-[var(--muted)] leading-relaxed">
                        <span className="text-[var(--foreground)] font-medium">
                          {labels.issuesLabel}:
                        </span>{' '}
                        {p.issues.map((i) => translateIssue(i)).join(' · ')}
                      </p>
                    ) : null}
                  </li>
                );
              })}
            </ul>
          </div>
        ) : null}
      </div>
    </details>
  );
}

function ScoreBox({ label, value }: { label: string; value: number }) {
  const tone =
    value >= 75
      ? 'text-[var(--success)]'
      : value >= 50
        ? 'text-[var(--warning)]'
        : 'text-[var(--danger)]';
  return (
    <div className="flex flex-col items-center gap-1 p-3 rounded-md bg-[var(--background)] border border-[var(--border)]">
      <span className="text-xs text-[var(--muted)] uppercase tracking-wider font-mono">
        {label}
      </span>
      <span className={`text-2xl font-bold tabular-nums ${tone}`}>{value}</span>
    </div>
  );
}

function ProductCaseStudy({
  index,
  product,
  labels
}: {
  index: number;
  product: SharedProduct;
  labels: {
    source: string;
    ai: string;
    title: string;
    description: string;
    tags: string;
    images: string;
    noTitle: string;
    noDescription: string;
    noTags: string;
    noImages: string;
  };
}) {
  const sourceText =
    product.source.descriptionHtml
      .replace(/<[^>]+>/g, ' ')
      .replace(/\s+/g, ' ')
      .trim() || labels.noDescription;
  const sourceTitle = decodeHtmlEntities(product.title ?? '');
  const aiTitle = product.ai.title ? decodeHtmlEntities(product.ai.title) : null;
  return (
    <Card variant="secondary" className="p-6 flex flex-col gap-5">
      <div className="flex items-baseline justify-between gap-3 flex-wrap">
        <h3 className="text-xl font-bold tracking-tight">
          <span className="text-[var(--muted)] mr-2">#{index}</span>
          {sourceTitle}
        </h3>
      </div>

      <div className="grid md:grid-cols-2 gap-5">
        {/* Source column ------------------------------------------- */}
        <div className="flex flex-col gap-3">
          <span className="eyebrow">{labels.source}</span>
          <Field label={labels.title} value={sourceTitle} muted={false} />
          <Field
            label={labels.description}
            value={sourceText}
            muted={!product.source.descriptionHtml}
            multiline
          />
          <Field
            label={labels.tags}
            value={product.source.tags.length > 0 ? product.source.tags.join(', ') : labels.noTags}
            muted={product.source.tags.length === 0}
          />
          <ImageRow
            label={labels.images}
            urls={product.source.images.map((i) => i.src)}
            emptyLabel={labels.noImages}
          />
        </div>

        {/* AI column ----------------------------------------------- */}
        <div className="flex flex-col gap-3">
          <span className="eyebrow inline-flex items-center gap-2">
            {labels.ai}
            <Sparkles className="size-3 text-[var(--accent)]" aria-hidden />
          </span>
          <Field label={labels.title} value={aiTitle ?? labels.noTitle} muted={!aiTitle} />
          <AiHtmlField
            label={labels.description}
            html={product.ai.descriptionHtml}
            empty={labels.noDescription}
          />
          <Field
            label={labels.tags}
            value={product.ai.tags.length > 0 ? product.ai.tags.join(', ') : labels.noTags}
            muted={product.ai.tags.length === 0}
          />
          <ImageRow
            label={labels.images}
            urls={product.ai.imageUrls}
            emptyLabel={labels.noImages}
            ai
          />
        </div>
      </div>
    </Card>
  );
}

function Field({
  label,
  value,
  muted,
  multiline = false
}: {
  label: string;
  value: string;
  muted: boolean;
  multiline?: boolean;
}) {
  return (
    <div className="flex flex-col gap-1">
      <span className="text-xs font-mono uppercase tracking-wider text-[var(--muted)]">
        {label}
      </span>
      <p
        className={`text-sm leading-relaxed ${muted ? 'text-[var(--muted)] italic' : ''} ${
          multiline ? 'line-clamp-6' : 'line-clamp-2'
        }`}
      >
        {value}
      </p>
    </div>
  );
}

function AiHtmlField({
  label,
  html,
  empty
}: {
  label: string;
  html: string | null;
  empty: string;
}) {
  return (
    <div className="flex flex-col gap-1">
      <span className="text-xs font-mono uppercase tracking-wider text-[var(--muted)]">
        {label}
      </span>
      {html ? (
        // The AI description is HTML produced by the optim flow with a
        // tightly-scoped tag set (<p>, <ul>, <li>, <strong>, etc.). We
        // render it via dangerouslySetInnerHTML for fidelity; the flow
        // never produces script tags. Wrapped in `prose` for spacing.
        <div
          className="prose text-sm max-w-none"

          dangerouslySetInnerHTML={{ __html: html }}
        />
      ) : (
        <p className="text-sm text-[var(--muted)] italic">{empty}</p>
      )}
    </div>
  );
}

function ImageRow({
  label,
  urls,
  emptyLabel,
  ai = false
}: {
  label: string;
  urls: string[];
  emptyLabel: string;
  ai?: boolean;
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <span className="text-xs font-mono uppercase tracking-wider text-[var(--muted)] inline-flex items-center gap-1.5">
        {label}
        {ai ? <Sparkles className="size-3 text-[var(--accent)]" aria-hidden /> : null}
      </span>
      {urls.length === 0 ? (
        <div className="aspect-[4/1] rounded-md bg-[var(--default)]/40 border border-[var(--border)] flex items-center justify-center text-xs text-[var(--muted)] italic">
          <ImageIcon className="size-4 mr-1.5 shrink-0" aria-hidden />
          {emptyLabel}
        </div>
      ) : (
        <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
          {urls.slice(0, 3).map((url, i) => (
            <ImageZoom
              key={`${url}-${i}`}
              url={url}
              alt={ai ? 'AI generated' : 'Source product image'}
              downloadName={ai ? `ai-${i + 1}.png` : `source-${i + 1}.jpg`}
            />
          ))}
        </div>
      )}
    </div>
  );
}
