import type { OptimHistoryItem } from '@/entities/generation-job';
import type { LoadedProduct } from '../model/types';

/**
 * The product page the tour shows when the merchant has no catalogue yet.
 *
 * It is not an overlay mimicking a product sheet: it is the real page, with
 * the real components, fed a sample product. A drawn mock taught the wrong
 * layout — the tester said as much — and the moment a real product exists
 * the tour points at that one instead.
 *
 * Nothing here touches the database. The row does not exist, so the page
 * renders it inert: no generation can be launched from it, no credit can be
 * spent, and it never appears in the catalogue, an export or a sync.
 *
 * The copy is OneShopLab's own (generated by the app on a test store) and the
 * two photographs are bundled under /public/tour, so the page does not depend
 * on a third-party CDN staying up.
 */
export const DEMO_DESCRIPTION_HTML = `<p><strong>Premium comfort meets everyday durability.</strong> Our Classic Crew Neck T-Shirt is engineered for all-day wear with a timeless design that works for men and women alike. Crafted from a carefully balanced fabric blend, this tee delivers softness without sacrificing structure or longevity.</p>
<p>The relaxed yet flattering fit works across body types, with reinforced seams and double-stitched construction throughout. Whether layering or wearing solo, you'll appreciate the reliable performance and fade-resistant quality that lasts wash after wash.</p>
<ul>
<li>Durable 5.3 oz fabric that keeps its shape</li>
<li>Reinforced, double-stitched seams at every stress point</li>
<li>Machine wash cold; tumble dry low for best results and color retention</li>
<li>Available in classic colors built to outlast trends</li>
</ul>
<p>Built for real life, not just the closet. The crew neck t-shirt is backed by consistent construction standards and tested for color fastness. Expect reliable performance, minimal shrinkage, and a dependable staple that earns its place in your rotation.</p>`;

const IMAGES = [
  {
    src: '/tour/demo-tshirt-1.webp',
    alt: 'Classic crew neck t-shirt, front view',
    width: 1200,
    height: 1200
  },
  {
    src: '/tour/demo-tshirt-2.webp',
    alt: 'Classic crew neck t-shirt, folded',
    width: 1200,
    height: 1200
  }
];

/** A complete LoadedProduct for the sample sheet, scoped to the caller's site. */
export function demoLoadedProduct(projectId: string): LoadedProduct {
  return {
    projectId,
    product: {
      sourceId: 'osl-demo-product',
      handle: 'crew-t-shirt',
      title: 'Classic Crew Neck T-Shirt for Men and Women',
      url: null,
      descriptionHtml: DEMO_DESCRIPTION_HTML,
      images: IMAGES.map((i) => ({ ...i })),
      variants: [
        { id: 'osl-demo-s', title: 'S', price: 120, options: { Size: 'S' } },
        { id: 'osl-demo-m', title: 'M', price: 120, options: { Size: 'M' } },
        { id: 'osl-demo-l', title: 'L', price: 120, options: { Size: 'L' } }
      ],
      score: 72,
      signals: {
        tags: ['t-shirt', 'cotton', 'unisex'],
        vendor: 'Sample Store',
        productType: 'T-Shirts',
        descriptionTextLength: 980,
        imageCount: IMAGES.length,
        priceMin: 120,
        priceMax: 120
      }
    },
    storeImages: IMAGES.map((i, index) => ({
      src: i.src,
      alt: i.alt,
      sourceImageId: `osl-demo-image-${index + 1}`
    })),
    archived: false,
    productInstructions: '',
    productImagePrompt: '',
    projectInstructions: '',
    isManual: false
  };
}

/**
 * A generation the sample product already went through.
 *
 * Without one there is nothing to send, so the send-to-store control — the
 * anchor of the tour's tenth step — does not render at all, and the step
 * lights up nothing. The entry is read-only like the rest of the sheet: the
 * page is inert, so its buttons cannot be pressed.
 */
export function demoOptimHistory(field: 'title' | 'description' | 'tags'): OptimHistoryItem[] {
  const output: Record<typeof field, string | string[]> = {
    title: 'Classic Crew Neck T-Shirt — Soft Cotton Blend for Men and Women',
    description:
      'Built for everyday wear: a balanced cotton blend that keeps its shape, ' +
      'reinforced seams at every stress point, and colour that survives the wash.',
    tags: ['t-shirt', 'cotton', 'unisex', 'everyday']
  };
  return [
    {
      jobId: `osl-demo-job-${field}`,
      field,
      userPrompt: '',
      output: output[field],
      createdAt: new Date(),
      creditsCost: field === 'description' ? 4 : 2,
      expiredAt: null
    }
  ];
}
